import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local"
import  { AuthProvider } from "../app/lib/AuthContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Kodchasan = localFont({
  src: [
    {
      path: "../public/fonts/fonts/Kodchasan-SemiBold.ttf",
      weight: "800",
      style: "normal",
    }
  ],
  variable: "--font-kodchasan"
})

const Manrope = localFont({
  src: [
    {
      path: "../public/fonts/fonts/Manrope-Regular.ttf",
      weight: "400",
      style: "normal",
    }
  ],
  variable: "--font-manrope"
})

const Manrope2 = localFont({
  src: [
    {
      path: "../public/fonts/fonts/Manrope-Bold.ttf",
      weight: "800",
      style: "normal",
    }
  ],
  variable: "--font-manropeSemiBold"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${Kodchasan.variable} ${Manrope.variable} ${Manrope2.variable} antialiased`}>
          <AuthProvider>
            {children}
          </AuthProvider>
      </body>
    </html>
  );
}
